analytics: {}
color:
  brandColors:
    - '#F0E8F0'
    - '#187808'
    - '#789050'
    - '#90D018'
    - '#90B0E0'
  brandStrength: 0.307432
  lightness: 0.275337
  rhythmicContrast: 0.171452
  saturation: 0.268581
cta: {}
layout_spectrum: 0.985641
name: 'Experience Living '
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.206925
