analytics: {}
color:
  brandColors:
    - '#C8D0D8'
    - '#000000'
    - '#808078'
    - '#000000'
    - '#000000'
  brandStrength: 1
  lightness: 0.209459
  rhythmicContrast: 0.933277
  saturation: 0.891891
cta: {}
layout_spectrum: 1
name: Wood Mizer
opengraph: {}
purpose: {}
typography_spectrum: 0
