name: 'Experience Living '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31047
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000008'
    - '#fff3d9'
    - '#0075df'
    - '#6ac4ff'
    - '#b19c64'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
