name: 'Experience Living '
layout_spectrum: 0.19099648646079004
typography_spectrum: 0.7442638755310327
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  brandStrength: 0.10894037061370909
  lightness: 0.25765685457736254
  saturation: 0.36307527776807547
  rhythmicContrast: 0.18020398658700287
purpose:
  - name: null
    item: null
    url: null
title: 'My Journey '
author:
  name: Mindy Tsolina
  url: ''
  email: beepresent.ms@gmail.com
content_rating:
  adult: false
favicon: null
coverPrefs:
  filter: false
