analytics: {}
color:
  brandColors:
    - '#B8C0C0'
    - '#6C1D19'
    - '#989078'
    - '#B03028'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.5
  rhythmicContrast: 0.171452
  saturation: 0.5
cta: {}
layout_spectrum: 0.807432
name: 'Experience Living '
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.327702
