analytics: {}
color:
  brandColors:
    - '#B0B8A0'
    - '#614E24'
    - '#808860'
    - '#D0B880'
    - '#E8E0C8'
  brandStrength: 1
  lightness: 0.505912
  rhythmicContrast: 0.751689
  saturation: 0.814189
cta: {}
layout_spectrum: 1
name: 'Experience Living '
opengraph: {}
purpose: {}
typography_spectrum: 0
