name: 'Experience Living '
favicon: null
layout_spectrum: 0.32932
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B8C0'
    - '#170C79'
    - '#888888'
    - '#2010A8'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.505912
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
