analytics: {}
color:
  brandColors:
    - '#72A8D6'
    - '#CDBDAD'
    - '#13519E'
    - '#968676'
    - '#FBFDFC'
  brandStrength: 0.664695
  lightness: 0.577702
  rhythmicContrast: 0.55152
  saturation: 0.552364
cta: {}
layout_spectrum: 0.016047
name: 'Experience Living '
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.20777
