analytics: {}
color:
  brandColors:
    - '#B8B8C0'
    - '#170C79'
    - '#888888'
    - '#2010A8'
    - '#000000'
  brandStrength: 1
  lightness: 0.505912
  rhythmicContrast: 0.751689
  saturation: 0.814189
cta: {}
layout_spectrum: 1
name: 'Experience Living '
opengraph: {}
purpose: {}
typography_spectrum: 0
