analytics: {}
color:
  brandColors:
    - '#B0B8A0'
    - '#614E24'
    - '#808860'
    - '#D0B880'
    - '#E8E0C8'
  brandStrength: 1
  lightness: 0.209459
  rhythmicContrast: 0.933277
  saturation: 0.891891
cta: {}
layout_spectrum: 1
name: Wood Mizer
opengraph: {}
purpose: {}
typography_spectrum: 0
