analytics: {}
color:
  brandColors:
    - '#C2E1FE'
    - '#FAFEFF'
    - '#A29285'
    - '#352E26'
    - '#857263'
  brandStrength: 0.664695
  lightness: 0.577702
  rhythmicContrast: 0.55152
  saturation: 0.552364
cta: {}
layout_spectrum: 0.193412
name: 'Experience Living '
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.20777
