analytics: {}
color:
  brandColors:
    - '#72A8D6'
    - '#CDBDAD'
    - '#13519E'
    - '#968676'
    - '#FBFDFC'
  brandStrength: 0.5
  lightness: 0.385135
  rhythmicContrast: 0.42652
  saturation: 0.655405
cta: {}
layout_spectrum: 0.226351
name: 'Experience Living '
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.43931
