analytics: {}
color:
  brandColors:
    - '#72a8d6'
    - '#c7b7a7'
    - '#1c5baa'
    - '#8d7d6d'
    - '#f3fefe'
  brandStrength: 0.5
  lightness: 0.385135
  rhythmicContrast: 0.42652
  saturation: 0.655405
cta: {}
layout_spectrum: 0.226351
name: 'Experience Living '
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.43931
