name: 'Experience Living '
favicon: null
layout_spectrum: 0.49446475389413536
typography_spectrum: 0.14123781700618565
coverPrefs:
  filter: false
title: 'My Journey '
author:
  name: Mindy Tsolina
  url: ''
  email: beepresent.ms@gmail.com
content_rating:
  adult: false
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
  brandStrength: 0.6094271009787917
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
