name: 'Experience Living '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000400'
    - '#8bd5ff'
    - '#1573a6'
    - '#88a624'
    - '#d8d560'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
