name: 'Experience Living '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31047
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#fd5451'
    - '#555555'
    - '#aeaeae'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
