name: 'Experience Living '
layout_spectrum: 0.193412
typography_spectrum: 0.31656
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#C2E1FE'
    - '#FAFEFF'
    - '#A29285'
    - '#352E26'
    - '#857263'
  brandStrength: 0.664695
  lightness: 0.577702
  saturation: 0.552364
  rhythmicContrast: 0.55152
purpose:
  - {}
title: 'My Journey '
author:
  name: Mindy Tsolina
  url: ''
  email: beepresent.ms@gmail.com
content_rating:
  adult: false
