analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#001200'
    - '#255500'
    - '#3B3922'
    - '#93C21A'
  brandStrength: 0.664695
  lightness: 0.577702
  rhythmicContrast: 0.55152
  saturation: 0.552364
cta: {}
layout_spectrum: 0.016047
name: 'Experience Living '
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.20777
