name: 'Experience Living '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43931
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#72a8d6'
    - '#c7b7a7'
    - '#1c5baa'
    - '#8d7d6d'
    - '#f3fefe'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
