name: 'Experience Living '
favicon: null
layout_spectrum: 0.193412
typography_spectrum: 0.31656
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C2E1FE'
    - '#FAFEFF'
    - '#A29285'
    - '#352E26'
    - '#857263'
  brandStrength: 0.664695
  lightness: 0.577702
  saturation: 0.552364
  rhythmicContrast: 0.55152
purpose:
  - name: null
    item: null
    url: null
